import { invoke } from '@tauri-apps/api/core';
import type {
  CacheReport,
  CategorySummary,
  CleanDeleteResult,
  CleanSummary,
  ConflictAction,
  ConflictDecision,
  DeleteResult,
  DirectoryListing,
  DriveStorage,
  DuplicateReport,
  FavoriteItem,
  FileProperties,
  HomeLocation,
  IndexedEntry,
  IndexProgress,
  JunkDeleteResult,
  OperationProgress,
  NearbyShare,
  PcShareSession,
  RecentItem,
  RenameOutcome,
  SearchFilter,
  SearchResults,
  Settings,
  ShareLink,
  TextPreview,
  Thumbnail,
  TransferPlan,
  TransferResult,
  UninstallCommand,
} from './specta-bindings';

export type {
  AppSource,
  BlockedItem,
  BlockedReason,
  CacheReport,
  CardAction,
  CategorySummary,
  CleanCard,
  CleanDeleteResult,
  CleanGroup,
  CleanItem,
  CleanSummary,
  ConflictAction,
  ConflictDecision,
  DeleteResult,
  DirectoryListing,
  DriveStorage,
  DuplicateFile,
  DuplicateReport,
  DuplicateSet,
  Exclusion,
  FavoriteItem,
  FileEntry,
  FileProperties,
  HomeLocation,
  IndexedEntry,
  IndexCounts,
  IndexProgress,
  InstalledApp,
  JunkDeleteResult,
  OperationProgress,
  NearbyShare,
  PcShareSession,
  OpsKind,
  OpsState,
  PlannedAction,
  PlannedConflict,
  PlannedItem,
  RecentItem,
  RecycleBinInfo,
  RenameOutcome,
  SearchFilter,
  SearchResults,
  Settings,
  ShareLink,
  SkippedFolder,
  TextPreview,
  Thumbnail,
  ThumbnailKind,
  TransferPlan,
  TransferResult,
  UninstallCommand,
} from './specta-bindings';

/** The only frontend boundary to native filesystem, thumbnail, and sharing commands. */
export const commands = {
  listHomeLocations: (): Promise<HomeLocation[]> => invoke('list_home_locations'),
  listDirectory: (path: string): Promise<DirectoryListing> => invoke('list_directory', { path }),
  /** The Clean tab's six cards, sized from the index, the junk walk and the registry. */
  getCleanSummary: (): Promise<CleanSummary> => invoke('get_clean_summary'),
  /** Hash-based duplicate scan; runs for minutes on a full profile, so it is separate. */
  scanDuplicates: (): Promise<DuplicateReport> => invoke('scan_duplicates'),
  cleanJunk: (groupIds: string[], expectedBytes: number): Promise<JunkDeleteResult> =>
    invoke('clean_junk', { groupIds, expectedBytes }),
  cleanPaths: (paths: string[]): Promise<CleanDeleteResult> => invoke('clean_paths', { paths }),
  emptyRecycleBin: (): Promise<number> => invoke('empty_recycle_bin'),
  uninstallApp: (command: UninstallCommand): Promise<void> => invoke('uninstall_app', { command }),
  searchFiles: (query: string): Promise<SearchResults> => invoke('search_files', { query }),
  openFile: (path: string): Promise<void> => invoke('open_file', { path }),
  startShare: (path: string): Promise<ShareLink> => invoke('start_share', { path }),
  stopShare: (): Promise<void> => invoke('stop_share'),
  startPcShare: (path: string): Promise<PcShareSession> => invoke('start_pc_share', { path }),
  stopPcShare: (): Promise<void> => invoke('stop_pc_share'),
  discoverPcShares: (): Promise<NearbyShare[]> => invoke('discover_pc_shares'),
  getPcShareProgress: (): Promise<number | null> => invoke('get_pc_share_progress'),
  getIndexStatus: (): Promise<IndexProgress> => invoke('get_index_status'),
  getCategorySummary: (): Promise<CategorySummary[]> => invoke('get_category_summary'),
  getDriveStorage: (): Promise<DriveStorage[]> => invoke('get_drive_storage'),
  listIndexDirectory: (path: string, sort: string, descending: boolean, limit: number, offset: number): Promise<IndexedEntry[]> =>
    invoke('list_index_directory', { path, sort, descending, limit, offset }),
  searchIndex: (filter: SearchFilter): Promise<IndexedEntry[]> => invoke('search_index', { filter }),

  /** Ask what a copy or move would do, including every name collision. */
  planTransfer: (paths: string[], destination: string, kind: 'copy' | 'move'): Promise<TransferPlan> =>
    invoke('plan_transfer', { paths, destination, kind }),
  copyPaths: (paths: string[], destination: string, decisions: ConflictDecision[], defaultAction: ConflictAction): Promise<TransferResult> =>
    invoke('copy_paths', { paths, destination, decisions, defaultAction }),
  movePaths: (paths: string[], destination: string, decisions: ConflictDecision[], defaultAction: ConflictAction): Promise<TransferResult> =>
    invoke('move_paths', { paths, destination, decisions, defaultAction }),
  renamePath: (path: string, newName: string, replace = false): Promise<RenameOutcome> =>
    invoke('rename_path', { path, newName, replace }),
  deletePaths: (paths: string[]): Promise<DeleteResult> => invoke('delete_paths', { paths }),
  cancelOperation: (jobId: string): Promise<boolean> => invoke('cancel_operation', { jobId }),
  listOperations: (): Promise<OperationProgress[]> => invoke('list_operations'),

  revealInExplorer: (path: string): Promise<void> => invoke('reveal_in_explorer', { path }),
  openWith: (path: string): Promise<void> => invoke('open_with', { path }),
  showProperties: (path: string): Promise<void> => invoke('show_properties', { path }),

  getThumbnail: (path: string): Promise<Thumbnail> => invoke('get_thumbnail', { path }),
  describePath: (path: string): Promise<FileProperties> => invoke('describe_path', { path }),
  readTextPreview: (path: string): Promise<TextPreview> => invoke('read_text_preview', { path }),
  recordRecent: (path: string, name: string): Promise<void> => invoke('record_recent', { path, name }),

  listFavorites: (): Promise<FavoriteItem[]> => invoke('list_favorites'),
  addFavorite: (path: string, name: string, isDirectory: boolean): Promise<FavoriteItem[]> =>
    invoke('add_favorite', { path, name, isDirectory }),
  removeFavorite: (path: string): Promise<FavoriteItem[]> => invoke('remove_favorite', { path }),
  listRecents: (limit = 20): Promise<RecentItem[]> => invoke('list_recents', { limit }),
  clearRecents: (): Promise<void> => invoke('clear_recents'),

  /** Everything the Settings screen owns, including the folders Sift never indexes. */
  getSettings: (): Promise<Settings> => invoke('get_settings'),
  setTheme: (theme: 'system' | 'light' | 'dark'): Promise<Settings> => invoke('set_theme', { theme }),
  setScanSchedule: (schedule: 'on_launch' | 'daily' | 'weekly' | 'manual'): Promise<Settings> =>
    invoke('set_scan_schedule', { schedule }),
  /** Writes the per-user Windows Run key; resolves to what Windows actually kept. */
  setStartWithWindows: (enabled: boolean): Promise<boolean> => invoke('set_start_with_windows', { enabled }),
  addExclusion: (path: string): Promise<Settings> => invoke('add_exclusion', { path }),
  removeExclusion: (path: string): Promise<Settings> => invoke('remove_exclusion', { path }),

  /** Thumbnail cache size plus the folders the last scan passed over. */
  getCacheReport: (): Promise<CacheReport> => invoke('get_cache_report'),
  clearThumbnailCache: (): Promise<CacheReport> => invoke('clear_thumbnail_cache'),
  clearSkippedFolders: (): Promise<CacheReport> => invoke('clear_skipped_folders'),
};
